new build and fixed ddb

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -80,7 +80,7 @@ do
 	case $i in
 	--help|-h)
 		usage ;;
-	image=*|modules=*|fs=*|usrskel=*|check|--append-manifest|--create-disk|--create-zfs-disk|--use-openzfs) ;;
+	image=*|app=*|modules=*|fs=*|usrskel=*|check|--append-manifest|--create-disk|--create-zfs-disk|--use-openzfs) ;;
 	clean)
 		stage1_args=clean ;;
 	arch=*)
@@ -90,49 +90,6 @@ do
 		args+=("$i") ;;
 	esac
 done
-
-if [[ "${arch-}" == "aarch64" && -d "build/downloaded_packages/aarch64/toolchain/" ]]; then
-	. scripts/download_aarch64_toolchain.sh
-	export CROSS_PREFIX=aarch64-none-linux-gnu-
-fi
-
-make "${args[@]}" -f conf/Makefile -j1 config | tee build.out
-# check exit status of make
-status=${PIPESTATUS[0]}
-if [ $status -ne 0 ]
-then
-	echo "make -f conf/Makefile failed. Exiting from build script"
-	exit $status
-fi
-
-make "${args[@]}" ${stage1_args} | tee build.out
-# check exit status of make
-status=${PIPESTATUS[0]}
-if [ $status -ne 0 ]
-then
-	echo "make failed. Exiting from build script"
-	exit $status
-fi
-
-for i
-do
-	case $i in
-	clean)	# "build clean" is like "make clean" to clean the kernel,
-		# plus additional cleanups of all modules.
-		set -x
-		OSV_BASE=`pwd` ./scripts/module.py clean -q
-		exit;;
-	esac
-done
-
-# Find out where "make" decided to put its compilation results. We'll
-# put the images in the same place.
-if test ! -L build/last -o ! -f build/last/loader.o
-then
-	echo "'make stage1' did not leave expected results" >&2
-	exit 2
-fi
-OUT=build/`readlink build/last`
 
 # Look for arguments that look like "name=value", and set them in an
 # assoative array "vars". Also look for the "-j ..." parallelism option,
@@ -178,6 +135,50 @@ do
 	esac
 done
 
+if [[ "${arch-}" == "aarch64" && -d "build/downloaded_packages/aarch64/toolchain/" ]]; then
+	. scripts/download_aarch64_toolchain.sh
+	export CROSS_PREFIX=aarch64-none-linux-gnu-
+fi
+
+echo ${vars[app]} 
+make "${args[@]}" conf_application=${vars[app]} -f conf/Makefile -j1 config | tee build.out
+# check exit status of make
+status=${PIPESTATUS[0]}
+if [ $status -ne 0 ]
+then
+	echo "make -f conf/Makefile failed. Exiting from build script"
+	exit $status
+fi
+
+make "${args[@]}" ${stage1_args} | tee build.out
+# check exit status of make
+status=${PIPESTATUS[0]}
+if [ $status -ne 0 ]
+then
+	echo "make failed. Exiting from build script"
+	exit $status
+fi
+
+for i
+do
+	case $i in
+	clean)	# "build clean" is like "make clean" to clean the kernel,
+		# plus additional cleanups of all modules.
+		set -x
+		OSV_BASE=`pwd` ./scripts/module.py clean -q
+		exit;;
+	esac
+done
+
+# Find out where "make" decided to put its compilation results. We'll
+# put the images in the same place.
+if test ! -L build/last -o ! -f build/last/loader.o
+then
+	echo "'make stage1' did not leave expected results" >&2
+	exit 2
+fi
+OUT=build/`readlink build/last`
+
 # fs_size_mb is in megabytes (1024*1024 bytes)
 fs_size_mb=${vars[fs_size_mb]-512}
 # fs_size is in bytes
@@ -206,7 +207,7 @@ host_arch=$(uname -m)
 
 # Default manifest
 manifest=bootfs.manifest.skel
-fs_type=${vars[fs]-zfs}
+fs_type=${vars[fs]-ramfs}
 usrskel_arg=
 case $fs_type in
 zfs)
